"""Test adventure loading to ensure chapter entries are preserved."""

import json
from pathlib import Path
from tempfile import NamedTemporaryFile

import pytest

from dnd5e.core.loaders.json_loader import JsonDataLoader
from dnd5e.core.models.content import ContentType
from tests.test_helpers import reset_test_environment


class TestAdventureLoading:
    """Test cases for adventure loading functionality."""

    def setup_method(self) -> None:
        """Reset global state for complete isolation using service container."""
        reset_test_environment()

    def test_adventure_data_only_format_loads_entries(self):
        """Test that data-only adventure files load chapter entries correctly.

        This test verifies the fix for issue #87 where adventures with only
        a 'data' array (no metadata fields) would load with empty chapters.
        """
        # Create mock adventure data matching 5etools format
        # This represents the structure found in adventure-*.json files
        adventure_data = {
            "data": [
                {
                    "type": "section",
                    "name": "Introduction",
                    "id": "000",
                    "entries": [
                        "Welcome to this test adventure.",
                        "This introduction has multiple entries to verify loading.",
                    ],
                },
                {
                    "type": "section",
                    "name": "Chapter 1: The Quest Begins",
                    "id": "001",
                    "entries": [
                        "The adventure begins in a tavern.",
                        "A mysterious stranger approaches the party.",
                        "They are offered a quest to retrieve an ancient artifact.",
                    ],
                },
                {
                    "type": "section",
                    "name": "Epilogue",
                    "id": "099",
                    "entries": [
                        "The quest is complete.",
                        "The party has saved the day.",
                    ],
                },
            ]
        }

        # Create temporary file
        with NamedTemporaryFile(mode="w", suffix=".json", delete=False) as f:
            json.dump(adventure_data, f, indent=2)
            temp_path = Path(f.name)

        try:
            # Load using JsonDataLoader
            loader = JsonDataLoader(ContentType("adventure"))
            adventures = loader.load(temp_path)

            # Verify adventure was loaded
            assert len(adventures) == 1
            adventure = adventures[0]

            # Verify adventure has name (should be generated by loader)
            assert adventure.name is not None
            assert len(adventure.name) > 0

            # Verify adventure has proper source
            assert adventure.source is not None

            # Verify chapters were created with content
            assert len(adventure.contents) == 3

            # Verify first chapter
            intro_chapter = adventure.contents[0]
            assert intro_chapter.name == "Introduction"
            assert len(intro_chapter.entries) == 2
            assert "Welcome to this test adventure" in str(intro_chapter.entries[0])
            assert "This introduction has multiple entries" in str(
                intro_chapter.entries[1]
            )

            # Verify second chapter
            quest_chapter = adventure.contents[1]
            assert quest_chapter.name == "Chapter 1: The Quest Begins"
            assert len(quest_chapter.entries) == 3
            assert "The adventure begins in a tavern" in str(quest_chapter.entries[0])
            assert "A mysterious stranger approaches" in str(quest_chapter.entries[1])
            assert "They are offered a quest" in str(quest_chapter.entries[2])

            # Verify third chapter
            epilogue_chapter = adventure.contents[2]
            assert epilogue_chapter.name == "Epilogue"
            assert len(epilogue_chapter.entries) == 2
            assert "The quest is complete" in str(epilogue_chapter.entries[0])
            assert "The party has saved the day" in str(epilogue_chapter.entries[1])

        finally:
            # Clean up
            temp_path.unlink()

    def test_adventure_with_metadata_loads_correctly(self):
        """Test that adventures with metadata load correctly."""
        # Create adventure data with metadata (traditional format)
        adventure_data = {
            "name": "Test Adventure with Metadata",
            "id": "TEST-001",
            "source": {"abbreviation": "TEST", "name": "Test Source"},
            "data": [
                {
                    "type": "section",
                    "name": "Test Chapter",
                    "id": "001",
                    "entries": [
                        "This is a test entry in a chapter.",
                        "The chapter should load with this content.",
                    ],
                }
            ],
        }

        with NamedTemporaryFile(mode="w", suffix=".json", delete=False) as f:
            json.dump(adventure_data, f, indent=2)
            temp_path = Path(f.name)

        try:
            loader = JsonDataLoader(ContentType("adventure"))
            adventures = loader.load(temp_path)

            assert len(adventures) == 1
            adventure = adventures[0]

            # Verify metadata preserved
            assert adventure.name == "Test Adventure with Metadata"
            assert adventure.id == "TEST-001"

            # Verify content loaded
            assert len(adventure.contents) == 1
            chapter = adventure.contents[0]
            assert chapter.name == "Test Chapter"
            assert len(chapter.entries) == 2

        finally:
            temp_path.unlink()
