"""Test adventure loading to ensure chapter entries are preserved."""

import json
from pathlib import Path
from tempfile import NamedTemporaryFile
from unittest import IsolatedAsyncioTestCase

from dnd5e.core.loaders.json_loader import JsonDataLoader
from dnd5e.core.models.content import ContentType


class TestAdventureLoading(IsolatedAsyncioTestCase):
    """Test cases for adventure loading functionality."""

    async def test_adventure_data_only_format_loads_entries(self):
        """Test that data-only adventure files load chapter entries correctly.

        This test verifies the fix for issue #87 where adventures with only
        a 'data' array (no metadata fields) would load with empty chapters.
        """
        # Create mock adventure data matching 5etools format
        # This represents the structure found in adventure-*.json files
        adventure_data = {
            "data": [
                {
                    "type": "section",
                    "name": "Introduction",
                    "id": "000",
                    "entries": [
                        "Welcome to this test adventure.",
                        "This introduction has multiple entries to verify loading.",
                    ],
                },
                {
                    "type": "section",
                    "name": "Chapter 1: The Quest Begins",
                    "id": "001",
                    "entries": [
                        "The adventure begins in a tavern.",
                        "A mysterious stranger approaches the party.",
                        "They are offered a quest to retrieve an ancient artifact.",
                    ],
                },
                {
                    "type": "section",
                    "name": "Epilogue",
                    "id": "099",
                    "entries": [
                        "The quest is complete.",
                        "The party has saved the day.",
                    ],
                },
            ]
        }

        # Create temporary file
        with NamedTemporaryFile(mode="w", suffix=".json", delete=False) as f:
            json.dump(adventure_data, f, indent=2)
            temp_path = Path(f.name)

        try:
            # Load using JsonDataLoader
            loader = JsonDataLoader(ContentType.ADVENTURE)
            adventures = await loader.load(temp_path)

            # Verify adventure was loaded
            self.assertEqual(len(adventures), 1)
            adventure = adventures[0]

            # Verify adventure has name (should be generated by loader)
            self.assertIsNotNone(adventure.name)
            self.assertTrue(len(adventure.name) > 0)

            # Verify adventure has proper source
            self.assertIsNotNone(adventure.source)

            # Verify chapters were created with content
            self.assertEqual(len(adventure.contents), 3)

            # Verify first chapter
            intro_chapter = adventure.contents[0]
            self.assertEqual(intro_chapter.name, "Introduction")
            self.assertEqual(len(intro_chapter.entries), 2)
            self.assertIn(
                "Welcome to this test adventure", str(intro_chapter.entries[0])
            )
            self.assertIn(
                "This introduction has multiple entries", str(intro_chapter.entries[1])
            )

            # Verify second chapter
            quest_chapter = adventure.contents[1]
            self.assertEqual(quest_chapter.name, "Chapter 1: The Quest Begins")
            self.assertEqual(len(quest_chapter.entries), 3)
            self.assertIn(
                "The adventure begins in a tavern", str(quest_chapter.entries[0])
            )
            self.assertIn(
                "A mysterious stranger approaches", str(quest_chapter.entries[1])
            )
            self.assertIn("They are offered a quest", str(quest_chapter.entries[2]))

            # Verify third chapter
            epilogue_chapter = adventure.contents[2]
            self.assertEqual(epilogue_chapter.name, "Epilogue")
            self.assertEqual(len(epilogue_chapter.entries), 2)
            self.assertIn("The quest is complete", str(epilogue_chapter.entries[0]))
            self.assertIn(
                "The party has saved the day", str(epilogue_chapter.entries[1])
            )

        finally:
            # Clean up
            temp_path.unlink()

    async def test_adventure_with_metadata_loads_correctly(self):
        """Test that adventures with metadata load correctly."""
        # Create adventure data with metadata (traditional format)
        adventure_data = {
            "name": "Test Adventure with Metadata",
            "id": "TEST-001",
            "source": {"abbreviation": "TEST", "name": "Test Source"},
            "data": [
                {
                    "type": "section",
                    "name": "Test Chapter",
                    "id": "001",
                    "entries": [
                        "This is a test entry in a chapter.",
                        "The chapter should load with this content.",
                    ],
                }
            ],
        }

        with NamedTemporaryFile(mode="w", suffix=".json", delete=False) as f:
            json.dump(adventure_data, f, indent=2)
            temp_path = Path(f.name)

        try:
            loader = JsonDataLoader(ContentType.ADVENTURE)
            adventures = await loader.load(temp_path)

            self.assertEqual(len(adventures), 1)
            adventure = adventures[0]

            # Verify metadata preserved
            self.assertEqual(adventure.name, "Test Adventure with Metadata")
            self.assertEqual(adventure.id, "TEST-001")

            # Verify content loaded
            self.assertEqual(len(adventure.contents), 1)
            chapter = adventure.contents[0]
            self.assertEqual(chapter.name, "Test Chapter")
            self.assertEqual(len(chapter.entries), 2)

        finally:
            temp_path.unlink()
