"""LaTeX utility functions for text escaping and formatting."""


def escape_latex_text(text: str) -> str:
    """Escape special LaTeX characters and Unicode characters in text.

    This function provides comprehensive LaTeX escaping for both special LaTeX
    characters and Unicode characters that need special handling. It properly
    distinguishes between ASCII apostrophes (which should remain unchanged)
    and Unicode smart quotes (which need LaTeX replacements).

    This implementation matches the behavior of the original content renderer,
    where LaTeX commands get their braces escaped (e.g., \\textbackslash\\{\\}).

    Args:
        text: Text to escape for LaTeX output

    Returns:
        LaTeX-safe text with proper character escaping

    Note:
        - ASCII apostrophes (') remain unchanged for natural text like "Player's"
        - Unicode left single quote (') gets converted to LaTeX backtick
        - All other LaTeX special characters are properly escaped
        - LaTeX commands generated by this function have their braces escaped
    """
    if not text:
        return ""

    # Match the original content.py behavior: direct replacement without placeholders
    # This means that LaTeX commands will have their braces escaped too

    # LaTeX special characters (exact order from original content.py)
    latex_chars = {
        "\\": "\\textbackslash{}",
        "{": "\\{",
        "}": "\\}",
        "$": "\\$",
        "&": "\\&",
        "%": "\\%",
        "#": "\\#",
        "^": "\\textasciicircum{}",
        "_": "\\_",
        "~": "\\textasciitilde{}",
    }

    result = text
    for char, escape in latex_chars.items():
        result = result.replace(char, escape)

    # Unicode characters that need special handling in LaTeX
    # NOTE: Deliberately excludes ASCII apostrophe (') to fix the
    # "Player's" -> "Player`s" bug that was affecting multiple implementations
    unicode_replacements = {
        "—": "---",  # Em dash
        "–": "--",  # En dash
        """: "``",   # Left double quote
        """: "''",  # Right double quote
        "…": "\\ldots{}",  # Ellipsis
        "°": "\\textdegree{}",  # Degree symbol
        "©": "\\copyright{}",  # Copyright symbol
        "®": "\\textregistered{}",  # Registered trademark
        "™": "\\texttrademark{}",  # Trademark symbol
    }

    # Apply Unicode character replacements
    for char, replacement in unicode_replacements.items():
        result = result.replace(char, replacement)

    return result
